import "@mantine/core/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";
import { type Metadata } from "next";
import { Inter, Orbitron } from "next/font/google";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const theme = createTheme({
  primaryColor: "deepRed",
  fontFamily: "var(--font-inter)",
  headings: { fontFamily: "var(--font-orbitron)" },
  colors: {
    deepRed: [
      "#ffeaec",
      "#fcd4d7",
      "#f4a7ac",
      "#ec777e",
      "#e64f57",
      "#e3353f",
      "#e22732",
      "#c91a25",
      "#b41220",
      "#9e0419",
    ],
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => (
  <html
    className={`${orbitron.variable} ${inter.variable}`}
    lang="en"
    {...mantineHtmlProps}
  >
    <head>
      <ColorSchemeScript forceColorScheme="dark" />
    </head>
    <body>
      <MantineProvider forceColorScheme="dark" theme={theme}>
        {children}
      </MantineProvider>
    </body>
  </html>
);

export default RootLayout;
