import { ChakraProvider } from "@chakra-ui/react";
import { type Metadata } from "next";
import { Inter, Orbitron } from "next/font/google";

import { system } from "./theme";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => (
  <html className={`${orbitron.variable} ${inter.variable}`} lang="en">
    <body>
      <ChakraProvider value={system}>{children}</ChakraProvider>
    </body>
  </html>
);

export default RootLayout;
